/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Form;

import javax.swing.*;
import javax.swing.table.DefaultTableModel;
import Config.DBConnection;
import Config.Tengah;
import java.awt.Color;
import java.sql.SQLException;
import java.sql.ResultSet;

/**
 *
 * @author windows 7
 */
public class D_Kelas extends javax.swing.JFrame {
    String id, nama;
    /**
     * Creates new form D_Kelas
     */
    public D_Kelas() {
        initComponents();
        cbwakel();
        TampilData();
        setLocationRelativeTo(this);
        txtwakel.setVisible(false);
    }
    
    public void kosong(){
        txt_id.setText("");
        txt_nama.setText("");
        cbwakel.setSelectedIndex(-0);
        txt_id.requestFocusInWindow();
    }
    
    private void TampilData() {
        //membuat tampilan model tabel
        DefaultTableModel model = new DefaultTableModel();
        //model.addColumn("NO");
        model.addColumn("KODE KELAS");
        model.addColumn("NAMA KELAS");
        model.addColumn("WALI KELAS");
        tblkelas.setModel(model);

        //menampilkan data database kedalam tabel
        try {
            //int i=1;
            java.sql.Connection conn = new DBConnection().connect();
            java.sql.Statement stat = conn.createStatement();
            ResultSet data = stat.executeQuery("SELECT id_kelas, nama_kelas, wali_kelas FROM p_kelas");
            while (data.next()) {
                model.addRow(new Object[]{
                    //("" + i++),
                    data.getString("id_kelas"),
                    data.getString("nama_kelas"),
                    data.getString("wali_kelas")
                });
                tblkelas.setModel(model);
            }
        } catch (Exception e) {
            System.err.println("ERROR:" + e);
        }
    }
    
    private void cbwakel() {
        cbwakel.removeAllItems();
        cbwakel.addItem("Pilih Wali Kelas");
        try {
            java.sql.Connection conn = new DBConnection().connect();
            java.sql.Statement stat = conn.createStatement();
            String sql_tc = "select kd_guru, nama_guru from p_guru";
            ResultSet rs = stat.executeQuery(sql_tc);

            while (rs.next()) {
                String nama = rs.getString("nama_guru");
                cbwakel.addItem(nama);
            }
            rs.close();
            stat.close();
        } catch (Exception e) {
            System.out.println(e.getMessage());
        }
    }

    public void cari_wakel() {
        try {
            java.sql.Connection conn = new DBConnection().connect();
            java.sql.Statement stat = conn.createStatement();
            String sql_t = "select kd_guru from p_guru where nama_guru ='" +  cbwakel.getSelectedItem() + "'";
            ResultSet rs = stat.executeQuery(sql_t);                              // yang anda ingin kan

            while (rs.next()) {
                this.txtwakel.setText(rs.getString("kd_guru"));
            }
            rs.close();
            stat.close();

        } catch (Exception e) {
            System.out.println(e.getMessage());
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel6 = new javax.swing.JPanel();
        jPanel10 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblkelas = new javax.swing.JTable();
        jPanel2 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txt_id = new javax.swing.JTextField();
        txt_nama = new javax.swing.JTextField();
        cbwakel = new javax.swing.JComboBox<>();
        txtwakel = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        bsimpan = new javax.swing.JButton();
        bubah = new javax.swing.JButton();
        bcari = new javax.swing.JButton();
        bbatal = new javax.swing.JButton();
        bhapus = new javax.swing.JButton();
        jPanel5 = new javax.swing.JPanel();
        jPanel7 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jPanel8 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jPanel9 = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();

        setPreferredSize(new java.awt.Dimension(950, 567));
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(245, 245, 245));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel6.setBackground(new java.awt.Color(44, 52, 82));
        jPanel1.add(jPanel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 536, 950, 30));

        jPanel10.setBackground(new java.awt.Color(255, 255, 255));
        jPanel10.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tblkelas.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        tblkelas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "KODE KELAS", "NAMA KELAS", "Title 3"
            }
        ));
        tblkelas.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblkelasMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblkelas);

        jPanel10.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 290, 630, 110));

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Masukkan Data", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("OCR A Extended", 1, 14), new java.awt.Color(51, 51, 51))); // NOI18N
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel5.setFont(new java.awt.Font("Century", 1, 13)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(102, 102, 102));
        jLabel5.setText("Kode Kelas");
        jPanel2.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 30, -1, 20));

        jLabel2.setFont(new java.awt.Font("Century", 1, 13)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(102, 102, 102));
        jLabel2.setText("Nama Kelas");
        jPanel2.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 75, -1, 20));

        txt_id.setBackground(new Color (0, 0, 0, 0));
        txt_id.setFont(new java.awt.Font("Ebrima", 0, 13)); // NOI18N
        txt_id.setForeground(new java.awt.Color(51, 51, 51));
        txt_id.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        txt_id.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(204, 204, 204), 1, true));
        txt_id.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_idActionPerformed(evt);
            }
        });
        jPanel2.add(txt_id, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 28, 180, 25));

        txt_nama.setBackground(new Color (0, 0, 0, 0));
        txt_nama.setFont(new java.awt.Font("Ebrima", 0, 13)); // NOI18N
        txt_nama.setForeground(new java.awt.Color(51, 51, 51));
        txt_nama.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        txt_nama.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(204, 204, 204), 1, true));
        jPanel2.add(txt_nama, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 75, 350, 25));

        cbwakel.setFont(new java.awt.Font("Ebrima", 0, 13)); // NOI18N
        cbwakel.setMaximumRowCount(9);
        cbwakel.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cbwakelItemStateChanged(evt);
            }
        });
        cbwakel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                cbwakelMouseClicked(evt);
            }
        });
        jPanel2.add(cbwakel, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 120, -1, 30));

        txtwakel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtwakelActionPerformed(evt);
            }
        });
        jPanel2.add(txtwakel, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 120, 53, 20));

        jLabel1.setFont(new java.awt.Font("Century", 1, 13)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(102, 102, 102));
        jLabel1.setText("Wali Kelas");
        jPanel2.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 125, -1, -1));

        jPanel10.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 10, 570, 170));

        jPanel4.setBackground(new java.awt.Color(255, 255, 255));
        jPanel4.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Proses", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("OCR A Extended", 1, 14), new java.awt.Color(51, 51, 51))); // NOI18N
        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        bsimpan.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/Save.png"))); // NOI18N
        bsimpan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bsimpanActionPerformed(evt);
            }
        });
        jPanel4.add(bsimpan, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 30, 100, 22));

        bubah.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/update2.png"))); // NOI18N
        bubah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bubahActionPerformed(evt);
            }
        });
        jPanel4.add(bubah, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 30, 100, 22));

        bcari.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/search2.png"))); // NOI18N
        bcari.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bcariActionPerformed(evt);
            }
        });
        jPanel4.add(bcari, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 30, 100, 22));

        bbatal.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/cancel2.png"))); // NOI18N
        bbatal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bbatalActionPerformed(evt);
            }
        });
        jPanel4.add(bbatal, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 30, 100, 22));

        bhapus.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/delete2.png"))); // NOI18N
        bhapus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bhapusActionPerformed(evt);
            }
        });
        jPanel4.add(bhapus, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 30, 100, 22));

        jPanel10.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 190, 570, 80));

        jPanel1.add(jPanel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 116, 710, 410));

        jPanel5.setBackground(new java.awt.Color(44, 52, 82));
        jPanel5.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel7.setBackground(new java.awt.Color(44, 52, 82));
        jPanel7.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel3.setBackground(new java.awt.Color(60, 135, 193));
        jLabel3.setFont(new java.awt.Font("Haettenschweiler", 0, 26)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/-school_902262.png"))); // NOI18N
        jLabel3.setText("SMAN 1 BATU LAYAR");
        jPanel7.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(17, 20, -1, -1));

        jPanel5.add(jPanel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 210, 70));

        jLabel11.setFont(new java.awt.Font("Ebrima", 1, 14)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setText("Logout");
        jLabel11.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel11MouseClicked(evt);
            }
        });
        jPanel5.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(890, 40, -1, -1));

        jPanel1.add(jPanel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 950, 70));

        jPanel8.setBackground(new java.awt.Color(0, 0, 17));
        jPanel8.setForeground(new java.awt.Color(51, 51, 51));
        jPanel8.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel6.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/dashboard_icon-icons2.png"))); // NOI18N
        jLabel6.setText(" Dashboard");
        jLabel6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel6MouseClicked(evt);
            }
        });
        jPanel8.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 30, -1, -1));

        jLabel7.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/w3586376-book-education-learning-teacher_107951.png"))); // NOI18N
        jLabel7.setText(" Data Siswa");
        jLabel7.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel7MouseClicked(evt);
            }
        });
        jPanel8.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 180, -1, -1));

        jLabel8.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/profesor2.png"))); // NOI18N
        jLabel8.setText(" Data Guru");
        jLabel8.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel8MouseClicked(evt);
            }
        });
        jPanel8.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 80, 120, -1));

        jLabel9.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/content-window_icon-icons2.png"))); // NOI18N
        jLabel9.setText(" Mata Pelajaran");
        jLabel9.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel9MouseClicked(evt);
            }
        });
        jPanel8.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 230, -1, -1));

        jLabel4.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/-class_900852.png"))); // NOI18N
        jLabel4.setText(" Data Kelas");
        jLabel4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel4MouseClicked(evt);
            }
        });
        jPanel8.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 130, -1, -1));

        jPanel9.setBackground(new java.awt.Color(17, 17, 40));
        jPanel9.setForeground(new java.awt.Color(20, 20, 20));

        javax.swing.GroupLayout jPanel9Layout = new javax.swing.GroupLayout(jPanel9);
        jPanel9.setLayout(jPanel9Layout);
        jPanel9Layout.setHorizontalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 200, Short.MAX_VALUE)
        );
        jPanel9Layout.setVerticalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 60, Short.MAX_VALUE)
        );

        jPanel8.add(jPanel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 110, 200, 60));

        jPanel1.add(jPanel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 66, 200, 500));

        jLabel10.setFont(new java.awt.Font("Century", 1, 24)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(102, 102, 102));
        jLabel10.setText("Data Kelas");
        jPanel1.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 70, -1, 40));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 950, 567));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void bsimpanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bsimpanActionPerformed
        java.sql.Connection conn = new DBConnection().connect();
        String id = txt_id.getText();
        String nama= txt_nama.getText();
        String wakel = (String) cbwakel.getSelectedItem();
        if (txt_id.getText().trim().equals("")) {
            JOptionPane.showMessageDialog(null, "Tolong masukan data anda ", "PERHATIAN", JOptionPane.WARNING_MESSAGE);
        } else {
            try {
                java.sql.Statement stat = conn.createStatement();
                ResultSet data = stat.executeQuery("SELECT * FROM p_kelas WHERE id_kelas ='" + txt_id.getText() + "'");
                if (data.next()) {
                    JOptionPane.showMessageDialog(null, "Kode Kelas telah terdaftar", "PERHATIAN", JOptionPane.WARNING_MESSAGE);
                    txt_id.requestFocus();
                } else {
                    String sql = "INSERT INTO p_kelas (id_kelas, nama_kelas, wali_kelas) VALUES('" + id + "'"
                    + ",'" + nama + "'"
                    + ",'" + wakel + "')";
                    stat.executeUpdate(sql);
                    kosong();
                    JOptionPane.showMessageDialog(null, "Penyimpanan Berhasil", "BERHASIL", JOptionPane.INFORMATION_MESSAGE);
                    TampilData();
                    //tampilmata_kuliah("SELECT * FROM p_siswa");
                }
                stat.close();
            } catch (Exception exc) {
                System.err.println("ERROR:" + exc);
            }
        }
    }//GEN-LAST:event_bsimpanActionPerformed

    private void bubahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bubahActionPerformed
        java.sql.Connection conn = new DBConnection().connect();
        int ok = JOptionPane.showConfirmDialog(null, "Apakah anda yakin mengubah data ini?", "DIALOG CONFIRMATION", JOptionPane.YES_NO_OPTION);
        if (ok == 0) {
            String sql = "update p_kelas set id_kelas='" + txt_id.getText()
            + "',nama_kelas='" + txt_nama.getText()
            + "',wali_kelas='" + cbwakel.getSelectedItem()
            + "'where id_kelas='" + txt_id.getText().trim() + "'";
            if (txt_id.getText().trim().equals("")) {
                JOptionPane.showMessageDialog(null, "Data Masih Kosong!", "UBAH DATA", JOptionPane.WARNING_MESSAGE);
                txt_id.requestFocus();
            } else {
                try {
                    java.sql.Statement stat = conn.createStatement();
                    stat.executeUpdate(sql);
                    JOptionPane.showMessageDialog(null, "Berhasil mengubah data", "UBAH DATA", JOptionPane.INFORMATION_MESSAGE);
                    stat.close();
                    txt_id.requestFocus();
                    TampilData();
                    //tampilmata_kuliah("SELECT * FROM p_siswa");
                } catch (Exception exc) {
                    System.err.println("Error :" + exc);
                }
            }
        }
    }//GEN-LAST:event_bubahActionPerformed

    private void bcariActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bcariActionPerformed
        java.sql.Connection conn = new DBConnection().connect();
        try {
            java.sql.Statement stat = conn.createStatement();
            ResultSet data = stat.executeQuery("SELECT * FROM p_kelas WHERE " + "id_kelas='" + txt_id.getText() + "'");
            DefaultTableModel model = new DefaultTableModel();
            model.addColumn("KODE KELAS");
            model.addColumn("NAMA KELAS");
            model.addColumn("WALI KELAS");
            tblkelas.setModel(model);

            if (data.next()) {
                model.addRow(new Object[]{
                    data.getString("id_kelas"),
                    data.getString("nama_kelas"),
                    data.getString("wali_kelas")
                });
                tblkelas.setModel(model);
            } else {
                JOptionPane.showMessageDialog(null, "Data Tidak Ditemukan", "WARNING", JOptionPane.WARNING_MESSAGE);
            }
            stat.close();
        } catch (Exception e) {
            System.err.println("ERROR:" + e);
        }
    }//GEN-LAST:event_bcariActionPerformed

    private void bbatalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bbatalActionPerformed
        kosong();
    }//GEN-LAST:event_bbatalActionPerformed

    private void bhapusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bhapusActionPerformed
        int ok = JOptionPane.showConfirmDialog(null, "Apakah anda yakin menghapus data ini?", "KONFIRMASI DIALOG", JOptionPane.YES_NO_OPTION);
        if (ok == 0) {
            java.sql.Connection conn = new DBConnection().connect();
            String sql = "DELETE FROM p_kelas WHERE id_kelas='" + txt_id.getText().trim() + "'";
            try {
                java.sql.Statement stat = conn.createStatement();
                stat.executeUpdate(sql);
                JOptionPane.showMessageDialog(null, "Berhasil menghapus data", "HAPUS DATA", JOptionPane.INFORMATION_MESSAGE);
                stat.close();
                kosong();
                TampilData();
                //tampilmata_kuliah("SELECT * FROM p_siswa");
            } catch (SQLException exc) {
                System.err.println(sql);
                System.err.println("ERROR: " + exc);
            }
        }
    }//GEN-LAST:event_bhapusActionPerformed

    private void tblkelasMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblkelasMouseClicked
        int baris = tblkelas.getSelectedRow();
        if (baris != 1) {
            txt_id.setText(tblkelas.getValueAt(baris, 0).toString());
            txt_nama.setText(tblkelas.getValueAt(baris, 1).toString());
        }
        cbwakel.setSelectedItem(tblkelas.getValueAt(baris, 2).toString());
    }//GEN-LAST:event_tblkelasMouseClicked

    private void txt_idActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_idActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_idActionPerformed

    private void jLabel7MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel7MouseClicked
        // TODO add your handling code here:
        new D_Siswa().setVisible(true);
        dispose();
    }//GEN-LAST:event_jLabel7MouseClicked

    private void jLabel8MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel8MouseClicked
        // TODO add your handling code here:
        new D_Guru().setVisible(true);
        dispose();
    }//GEN-LAST:event_jLabel8MouseClicked

    private void jLabel9MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel9MouseClicked
        // TODO add your handling code here:
        new D_MataPelajaran().setVisible(true);
        dispose();
    }//GEN-LAST:event_jLabel9MouseClicked

    private void jLabel4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel4MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel4MouseClicked

    private void cbwakelItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cbwakelItemStateChanged
        // TODO add your handling code here:
        cari_wakel();
    }//GEN-LAST:event_cbwakelItemStateChanged

    private void cbwakelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cbwakelMouseClicked
        // TODO add your handling code here:
        cari_wakel();
    }//GEN-LAST:event_cbwakelMouseClicked

    private void txtwakelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtwakelActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtwakelActionPerformed

    private void jLabel11MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel11MouseClicked
        // TODO add your handling code here:
        int selectedoption = JOptionPane.showConfirmDialog(null, "Apakah anda ingin keluar dari akun?", "KELUAR AKUN",
            JOptionPane.YES_NO_OPTION);
        if (selectedoption == JOptionPane.YES_OPTION) {
            new Login().setVisible(true);
            dispose();
        }
    }//GEN-LAST:event_jLabel11MouseClicked

    private void jLabel6MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel6MouseClicked
        // TODO add your handling code here:
        new AdminData().setVisible(true);
        dispose();
    }//GEN-LAST:event_jLabel6MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(D_Kelas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(D_Kelas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(D_Kelas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(D_Kelas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new D_Kelas().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bbatal;
    private javax.swing.JButton bcari;
    private javax.swing.JButton bhapus;
    private javax.swing.JButton bsimpan;
    private javax.swing.JButton bubah;
    private javax.swing.JComboBox<String> cbwakel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblkelas;
    private javax.swing.JTextField txt_id;
    private javax.swing.JTextField txt_nama;
    private javax.swing.JTextField txtwakel;
    // End of variables declaration//GEN-END:variables
}
